manzt/zarrita.js

README.md, package.json, src/core.js, src/fsstore.js, src/index.js, src/indexing.js, src/ops.js, test/common.js, test/fsstore.test.js, test/memstore.test.js
Mutates the `ZarrArray` prototype to add indexing/slicing + `get`/`set` methods for the array. Thus, the library is totally tree-shakeable:
```javascript
import { get_hierarchy } from 'zarrita/core'; // minimal hierarchy code + get_chunk by key for arrays
const h = await get_hierarchy(store);
const a = await h.get('/arr');
a.get(null) // throws NotImplementedError
const chunk_coords = [0, 0];
a.get_chunk(chunk_coords) // returns Promise for decoded chunk
```
```javascript
import { get_hierarchy, slice } from 'zarrita';
const h = await get_hierarchy(store);
const a = await h.get('/arr');
a.get([slice(null), slice(null, null, 2)]) // returns promise for array
```
=> Separate core module and add indexing & slicing

package.json, src/core.js, src/errors.js, src/fsstore.js, src/indexing.js, src/zarrita.js
Moves the core of indexing into a separate modules so that they can be reused (e.g. in `zarr-lite`).
Also, the logic in `opts.js` logic requires that the `out_shape` not be squeezed. This PR makes it so that the `out` array is initialize to the "unsqueezed" shape and then integer dim selections are only "squeezed" after it is filled.
=> Move indexing and errors into reuseable modules

package.json
Oop, using code splitting in #6 creates a hashed chunk that didn't get published to NPM. This fixes the issue.
=> Add hashed-chunks to published build

package.json
Since we mutate the `ZarrArray.prototype` in `src/zarrita.js`, we need to mark this module as having sideEffects and that it shouldn't be tree-shaken.
=> Mark top level exports as having side effects

package.json, pnpm-lock.yaml, src/index.js, src/lib/custom-arrays.js, src/lib/get.js, src/lib/helpers.js, src/lib/hierarchy.js, src/lib/ops.js, src/lib/util.js, src/storage/fetch.js, src/types.d.ts
Adds `BoolArray`, `UinicodeStringArray` and `ByteStringArray` data classes. These interfaces  adhere to the `generic` array datatype supported by `ndarray`, and also provide a helper method for reading the data as a simple javascript `Array`.
```typescript
interface GenericArray<T> {
get(i: number): T;
set(i: number, value: T): void;
length: number;
}
interface ZarritaArray<T> extends GenericArray<T> {
buffer: ArrayBuffer;
fill(value: T): void;
array(): Array<T> // collect underlying data into a JavaScript array
}
type BoolArray = ZarritaArray<boolean>;
type StringArray = ZarritaArray<string>; // UnicodeStringArray & ByteStringArray implement this differently.
```
Each class is backed by `DataView` of a linear `ArraryBuffer`; a much more efficient representation of the chunk-level data. I …
=> feat: support `b1` boolean, `S` &  `U` string data-types

src/lib/hierarchy.ts, src/storage/fetch.ts, src/storage/fs.ts, src/storage/mem.ts, src/types.ts, src/v2.ts, src/v3.ts, test/common.js
Return type is `never` for store that only implement `Readable`:
=> Use conditional types to allow readonly store implementations

package.json, pnpm-lock.yaml, src/dtypes.ts, src/lib/custom-arrays.ts, src/lib/util.ts, tests/get-v2.ts
Type inference for the number of chars in a str datatype is possible, but it currently breaks type narrowing with a custom type guard.  This PR removes all the fancy inference, so that useful custom type guards are possible:
```typescript
import type * as zarr from "zarrita/v2";
import type { DataType, Readable, Async, AbsolutePath } from "zarrita/types";
function is<
D extends DataType,
Store extends Readable | Async<Readable>,
Path extends AbsolutePath,
>(
arr: zarr.Array<DataType, Store, Path>,
dtype: D,
): arr is zarr.Array<D, Store, Path> {
return arr.dtype === dtype;
}
declare const arr: zarr.Array<DataType, Map<string, Uint8Array>, "/">;
declare const d: "|S43" | ">i2";
if (is(arr, d)) {
arr // zarr.Array<">i2" | "S43", Map<string, Uint8Array>, "/">
} 
```
=> Remove `Chars` generic for str datatypes

.changeset/shy-pigs-serve.md, package.json, packages/storage/__tests__/fetch.test.ts, packages/storage/__tests__/fs.test.ts, packages/storage/package.json, packages/storage/src/fetch.ts, packages/storage/src/ref.ts
- feat(storage): propagate RequestInit in FetchStore
- changesets
=> feat(storage): Configurable `RequestInit` from `FetchStore` constructor

.changeset/config.json, .github/workflows/ci.yml, README.md, dprint.json, package.json, pnpm-lock.yaml
`deno fmt` uses `dprint` under the hood. This PR configures `dprint` in "deno" mode, but using Node.js to run the package.
=> chore: replace deno fmt with dprint

.github/workflows/ci.yml, README.md, docs/get-started.md, index.html
- chore: use next tag in docs
- ci: lint published exports
=> docs: use next tag in getting started docs

.changeset/cold-dancers-chew.md, packages/indexing/src/ops.ts
All the array containers (except for `Array`) are backed by `ArrayBuffer`, but we currently have special handling for our string array containers.
This PR generalizes the indexing algorithm to operate on the "raw" bytes directly for any data. This way we _only_ move contigous blocks of binary data between src and target and avoid needing to move data out of the buffers into JS objects.
=> feat(indexing): generalize buffer-backed operations

packages/core/__tests__/open.test.ts, packages/core/src/open.ts, packages/storage/__tests__/fetch.test.ts, packages/storage/package.json, pnpm-lock.yaml
- Only count v2 vs. v3 for successful.
- Adds additional tests for switching priority v2 vs. v3
=> feat(core): only count successful opens

.changeset/serious-comics-lick.md, README.md, docs/cookbook.md, docs/packages/storage.md, docs/what-is-zarrita.md, packages/storage/src/types.ts
Uses the preferred and more common spelling for Writable interface.
=> fix(storage): Rename type `Writeable` to `Writable`

docs/packages/storage.md
@keller-mark: I think this resolves:
> Docs: Need to put requestInit in FetchStore(url, { overrides: requestInit });
also open to naming something more clear (i.e., `fetchOptions`).
=> docs(storage): Expand on FetchStore configuration

packages/core/src/util.ts, packages/indexing/__tests__/slice.test.ts, packages/ndarray/__tests__/slice.test.ts
In the migration to a monorepo, we weren't testing the ndarray slicing capabilities.
=> test(ndarray): Reuse slice_test suite

packages/ndarray/package.json
👋 I've been (finally!) playing around with integrating `@carbonplan/maps` with `zarrita`. It's been a pretty smooth transition, except when I have a basic import from `@zarrita/ndarray`
```js
import { get } from '@zarrita/ndarray'
```
I see the following error
```
Module not found: Package path . is not exported from package
/Users/katamartin/carbonplan/maps/node_modules/@zarrita/ndarray (see exports field in 
/Users/katamartin/carbonplan/maps/node_modules/@zarrita/ndarray/package.json)
```
I think this should be resolved by updating the `exports` for`@zarrita/ndarray` to point to the correct index files (and match the [`@zarrita/storage` exports](https://github.com/manzt/zarrita.js/blob/ee6a672904714d43dcbc8d97d1b89220ada16a3f/packages/storage/package.json#L12-L13)!). I haven't actually …
=> Update exports for `@zarrita/ndarray`

.changeset/popular-glasses-nail.md, package.json, packages/core/__tests__/consolidated.test.ts, packages/core/src/consolidated.ts, packages/core/src/errors.ts, packages/core/src/index.ts, packages/core/src/open.ts, packages/indexing/src/get.ts, packages/indexing/src/set.ts, packages/zarrita/index.test.ts
Towards #117
Introduces the `withConsolidated` store helper (?). Looks for v2 consolidated metadata,
and returns known `contents`. "Opening" paths from the store is essentially free for
consolidated data (and will not make a network request)
```ts
let store = await withConsolidated(new FetchStore("http://localhost:8080"));
let contents = store.contents() // [ {path: "/", kind: "group" }, { path: "/foo", kind: "array" }, ...]
let foo = await open(contents[1].path, { kind: "array" });
```
=> feat: add `withConsolidated` store helper

.changeset/green-pandas-argue.md, packages/core/__tests__/consolidated.test.ts, packages/core/__tests__/open.test.ts, packages/core/src/consolidated.ts, packages/core/src/index.ts, packages/zarrita/index.test.ts
Adds `tryWithConsolidated` helper to provide a consistent interface for reading from a store that may or may not be consolidated. Consolidated stores will not incur additional network requests when reading underlying groups and arrays.
=> feat(core): Add `tryWithConsolidated` helper

packages/core/src/consolidated.ts
Changes
```ts
import { type ... } from "@zarrita/storage";
```
to
```ts
import type { ... } from "@zarrita/storage"
```
so the import is dropped by TypeScript in the build output. Prevents bundlers from typing to import from `@zarrita/storage`.
=> fix(core): Avoid importing types from top-level @zarrita/storage

.changeset/lovely-readers-change.md, packages/core/__tests__/json2.test.ts, packages/core/src/codecs.ts, packages/core/src/codecs/json2.ts, packages/core/src/util.ts, packages/zarrita/index.test.ts
This is needed to support h5ad-via-kerchunk which embeds `json2`-encoded arrays of strings into the reference spec.
I ported this from the python implementation at https://github.com/zarr-developers/numcodecs/blob/0878717a3613d91a453fe3d3716aa9c67c023a8b/numcodecs/json.py#L34
=> Add json2 codec

.changeset/three-pots-matter.md, packages/storage/src/zip.ts
This pull request adds support for passing fetch options into the ZipFileStore when fromUrl, for example for authentication headers.
=> ZipFileStore overrides

.changeset/something.md, packages/storage/src/fetch.ts, packages/storage/src/ref.ts, packages/storage/src/util.ts
This pull request adds two options for the ReferenceStore:
- `overrides` to specify fetch options like auth headers
- ~Should these same overrides also be used in the fetch call within `ReferenceStore.fromUrl`?~
- ~`preferTarget` to denote that the `opts.target` URL should be used regardless of whether a URL is present in the reference JSON~
- I would also be open to removing this change if it is unfavorable as it can alternatively be achieved in user-land by the user manually null-ing the URLs within the contents of the ReferenceEntrys before passing into `fromSpec`
=> Add options for ReferenceStore

.changeset/odd-ties-clap.md, packages/storage/__tests__/ref.test.ts, packages/storage/src/ref.ts
=> ReferenceStore creation, non-async

.changeset/smooth-scissors-end.md, packages/storage/src/fetch.ts
`FetchStore` now throws an error for 403 (forbidden) responses. This is a **breaking** change because previously `404` and `403` responses were treated the same way. Now, only `404` responses signify a "missing" key from the store.
I believe this carries the correct semantics around 404 and 403 responses. If you disagree, please let me know and we can discuss how to extend the `FetchStore` to be more flexible with handling responses.
see: https://github.com/hms-dbmi/vizarr/pull/214
=> feat(storage)!: Throw an error for 403 HTTP responses

.changeset/clever-moose-hear.md, packages/core/src/codecs.ts, packages/core/src/codecs/bitround.ts, packages/zarrita/index.test.ts
Fixes #233. Introduces `BitroundCodec` with a no-op for decoding because
bit-rounding is lossy, and precision cannot be restored. Encoding is not
yet implemented, reflecting zarrita's current focus on read-heavy
contexts. Open an issue if encoding support is needed.
=> Support read-only `bitround` codec

.changeset/breezy-windows-notice.md, package.json, packages/core/src/codecs/vlen-utf8.ts, packages/core/src/metadata.ts, packages/typedarray/__tests__/index.test.ts, packages/typedarray/src/index.ts, pnpm-lock.yaml
TypeScript changed the typing behavior of all `TypedArray` objects to
now be generic over the underlying `ArrayBufferLike` type. In order to
have our types be consistent with these changes, we needed to specify
the `ArrayBuffer` explicitly, but that breaks for older versions of
TypeScript. This PR fixes the version of TypeScript to 5.6. We will need
to bump again when we want to support 5.7.
=> Fix TypedArray types for TypeScript < 5.7

package.json, packages/core/src/codecs/vlen-utf8.ts, packages/indexing/__tests__/setter.test.ts, packages/ndarray/package.json, packages/ndarray/src/missing-types.d.ts, packages/typedarray/__tests__/index.test.ts, packages/typedarray/src/index.ts, pnpm-lock.yaml
TypeScript 5.7 made TypeArray objects generic over an `ArrayBufferLike`
source. We only use `ArrayBuffer` internally, so isdeally we would be
explicit about the generic parameter in our return types. However, older
versions of TS will fail with an explicit generic parameter (i.e.,
`Uint8Array<ArrayBuffer>`).
The biggest issue is a mismatch between `ndarray` types and our own.
This change vendors the types for `ndarray`, to align them with our own.
=> Support TypeScript 5.6 and 5.7

packages/core/src/consolidated.ts, packages/core/src/open.ts, packages/core/src/util.ts
Add a custom type-safe util that ensures an error matches an expected
type, otherwise rethrows. Just cleans up some logic with fallback logic
and `NodeNotFoundError`.
=> Add `rethrow_unless` util for try/catch blocks

packages/core/src/codecs.ts, packages/core/src/codecs/bitround.ts, packages/core/src/codecs/json2.ts, packages/core/src/codecs/sharding.ts, packages/core/src/consolidated.ts, packages/core/src/util.ts, packages/storage/src/util.ts, packages/storage/src/zip.ts
Makes assertions more declarative throughout the codebase.
=> refactor: Add `assert` utility function

.changeset/rich-horses-count.md, packages/core/__tests__/consolidated.test.ts, packages/core/src/consolidated.ts
Previously, only `Readable.get` was propagated up. This makes sure we can also
use `Readable.getRange` if supported when the store is consolidated.
=> Propagate `getRange` support in `Listable` when available

.changeset/four-bats-knock.md, .changeset/nervous-boxes-exist.md, .changeset/quiet-queens-chew.md, packages/core/__tests__/open.test.ts, packages/core/__tests__/typedarray.test.ts, packages/core/__tests__/util.test.ts, packages/core/package.json, packages/core/src/codecs/transpose.ts, packages/core/src/index.ts, packages/core/src/metadata.ts, packages/core/src/typedarray.ts, packages/core/src/util.ts, packages/indexing/__tests__/get.test.ts, packages/ndarray/__tests__/index.test.ts, packages/typedarray/README.md, packages/typedarray/index.ts, packages/typedarray/package.json, packages/zarrita/index.test.ts, pnpm-lock.yaml
This also starts the deprecation of `@zarrita/typedarray`. It's a small
module and it makes sense to keep it in the core to simplify project
structure.
=> Consolidate `@zarrita/typedarray` into `@zarrita/core`

.changeset/late-tables-peel.md, packages/core/src/codecs/bytes.ts, packages/core/src/codecs/transpose.ts, packages/core/src/hierarchy.ts, packages/core/src/util.ts
Fixes #129
In a follow up PR, I'd like to potentially make `stride` a readonly property on `Chunk` interface and instead support an explicit _order_ instead.
=> feat(core): Support transpose with explicit permutation

.changeset/all-apples-beam.md, packages/@zarrita-ndarray/__tests__/index.test.ts, packages/zarrita/__tests__/indexing/get.test.ts, packages/zarrita/src/hierarchy.ts, packages/zarrita/src/indexing/get.ts, packages/zarrita/src/indexing/types.ts
I want to make a stable release of `zarrita` and this feature is not stable. We can focus on a PR after to support along with deciding on a new API if necessary.
=> Remove order from `GetOptions`

.changeset/tired-doodles-attack.md, packages/zarrita/src/codecs.ts, packages/zarrita/src/codecs/gzip.ts, packages/zarrita/src/codecs/zlib.ts, packages/zarrita/src/util.ts
This is a **breaking change**. Since usage of **zarrita** is primarily read-only, this change replaces the default `numcodecs/gzip` and `numcodecs/zlib` codecs with custom decode-only codecs based on the builtin `DecompressionStream` API.
These changes reduce dynamic imports and remove additional dependencies for the majority use case. Users who require encoding must explicitly register their own codecs from `numcodecs`.
```ts
import * as zarr from "zarrita";
import GZip from "numcodecs/gzip";
import Zlib from "numcodecs/zlib";
zarr.registry.set("gzip", () => GZip);
zarr.registry.set("zlib", () => Zlib);
```
=> feat!(zarrita): Replace `gzip`/`zlib` codecs with decode-only `DecompressionStream` implementation

.changeset/thick-owls-swim.md, tsconfig.json
Enables the generation of [sourcemap files](https://web.dev/articles/source-maps), which allow debuggers and other tools to display the original TypeScript source code when actually working with the emitted JavaScript files. 
This should provide better introspection of zarrita code.
=> Emit and publish sourcemaps

packages/@zarrita-ndarray/package.json, packages/@zarrita-storage/package.json, packages/zarrita/package.json
Fixes #293
Add `src/` directories to the files array in `package.json` for all
three packages (`zarrita`, `@zarrita/storage`, `@zarrita/ndarray`).
=> Include TypeScript source files to npm packages

.github/workflows/release.yml, package.json
Add `version` script to package.json that runs `scripts/sync-jsr.mjs` after versioning. Should allow our changesets to automatically trigger JSR releases as well, without needing to "sync" in a separate commit/PR.
=> Configure changesets to sync JSR manifests on version
